# Generated by Django 5.0.6 on 2024-05-28 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.PositiveIntegerField(null=True)),
                ("counselerId", models.PositiveIntegerField(null=True)),
                ("userName", models.CharField(max_length=40, null=True)),
                ("counselerName", models.CharField(max_length=40, null=True)),
                ("appointmentDate", models.DateField(auto_now=True)),
                ("description", models.TextField(max_length=500)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserDischargeDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.PositiveIntegerField(null=True)),
                ("userName", models.CharField(max_length=40)),
                ("assignedCounselerName", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20, null=True)),
                ("symptoms", models.CharField(max_length=100, null=True)),
                ("admitDate", models.DateField()),
                ("releaseDate", models.DateField()),
                ("daySpent", models.PositiveIntegerField()),
                ("roomCharge", models.PositiveIntegerField()),
                ("medicineCost", models.PositiveIntegerField()),
                ("counselerFee", models.PositiveIntegerField()),
                ("OtherCharge", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Counseler",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pic/CounselerProfilePic/",
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20, null=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("O level Counseling", "O level Counseling"),
                            ("A level Counseling", "A level Counseling"),
                            (
                                "Matric Science level Counseling",
                                "Matric Science level Counseling",
                            ),
                            (
                                "Fsc Pre-Medical Counseling",
                                "Fsc Pre-Medical Counseling",
                            ),
                            (
                                "Fsc Pre-Engineering Counseling",
                                "Fsc Pre-Engineering Counseling",
                            ),
                            ("ICS Counseling", "ICS Counseling"),
                        ],
                        default="ICS Counseling",
                        max_length=50,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pic/UserProfilePic/"
                    ),
                ),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.CharField(max_length=20)),
                ("symptoms", models.CharField(max_length=100)),
                ("assignedCounselerId", models.PositiveIntegerField(null=True)),
                ("admitDate", models.DateField(auto_now=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
