# Generated by Django 3.0.5 on 2024-06-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/CounsellorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('O level Counseling', 'O level Counseling'), ('A level Counseling', 'A level Counseling'), ('Matric Science level Counseling', 'Matric Science level Counseling'), ('Fsc Pre-Medical Counseling', 'Fsc Pre-Medical Counseling'), ('Fsc Pre-Engineering Counseling', 'Fsc Pre-Engineering Counseling'), ('ICS Counseling', 'ICS Counseling')], default='Cardiologist', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/StudentProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('assignedCounsellorId', models.PositiveIntegerField(null=True)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDischargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.PositiveIntegerField(null=True)),
                ('studentName', models.CharField(max_length=40)),
                ('assignedCounsellorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('counsellorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='counseler',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDischargeDetails',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='counselerId',
            new_name='counsellorId',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='counselerName',
            new_name='counsellorName',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='userId',
            new_name='studentId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='studentName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Counseler',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
