# Generated by Django 3.0.5 on 2024-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20240605_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='symptoms',
            new_name='studyArea',
        ),
        migrations.RenameField(
            model_name='studentdischargedetails',
            old_name='symptoms',
            new_name='studyArea',
        ),
    ]
